### ISSUE TITLE
Descriptions truncated in collections list

### ISSUE THREAD

**Issue by Rollbacke** [jorenn92/Maintainerr#1432]
**Describe the bug**
The description of the collections, which should be complete, is truncated in the list of collections.

**To Reproduce**
Just go in collection and watch descriptions.

**Expected behavior**
Complete description.

**Screenshots**
https://github.com/user-attachments/assets/8b7d9616-71b1-4382-abbb-a7241da61f57

**Device (please complete the following information):**
 - Browser: Firefox
 - Maintainerr version: 2.2.1

**Comment by Rollbacke** [comment]
It's purely cosmetic, it helps me remember which collection it is, but otherwise everything works fine.

**Comment by benscobie** [comment]
The truncation is on purpose, but it shouldn't be scrollable like that.

**Comment by benscobie** [comment]
This should be resolved in v2.5.0.

**Comment by Rollbacke** [comment]
Hey @benscobie,
Unfortunately, the issue is not resolved. Still present on 2.9.0.

https://github.com/user-attachments/assets/f83e438d-de4e-41dc-b62e-1becdc0beac8

**Comment by Rollbacke** [comment]
I didn't see that the "Rules" page had changed to look like the "Collections" page.
So I want to clarify that the problem is ONLY in the "Collections" page, not in the "Rules" page.

**Comment by benscobie** [comment]
Previously the text was completely cut off after 2 lines which I fixed, the scrolling is intentional to prevent large cards.

**Comment by Rollbacke** [comment]
I agree with you, and I think that's what should be done, but in the video, you can see the descriptions of the "En cours de suppression" collections (3) and (5) which are truncated, whereas there should be a scroll bar.
I don't explain why these and not the others...

**Comment by Rollbacke** [comment]
Maybe it's a size of sentence related. The "En cours de suppression" collections (3) and (5) are a little bit smaller than the other with the scroll bar.

**Comment by ydkmlt84** [comment]
> I agree with you, and I think that's what should be done, but in the video, you can see the descriptions of the "En cours de suppression" collections (3) and (5) which are truncated, whereas there should be a scroll bar. I don't explain why these and not the others...

Are you saying that the description on 3 and 5 has more content and should have a scrollbar like the others do?

**Comment by ydkmlt84** [comment]
> -Maybe it's size of sentence related. The "En cours de suppression" collections (3) and (5) are a little bit smaller than the other with the scroll bar.- Tested: no.

I haven't fixed it yet but I did discover that it only happens on the collections with background images. Or collections that have more than 1 item in them, which creates the background image. Still working on the fix.

**Comment by Rollbacke** [comment]
It looks solved. Weird because the PR wasn't merged.

**Comment by ydkmlt84** [comment]
It was fixed in a separate PR, as this one had some issues. So I just added into the latest one I was working on. Good to hear it's confirmed.

**Comment by Rollbacke** [comment]
Thanks, you rock !
